import type { Thought, ThoughtConnection } from "./philosophy";

const maoIdentity = {
  name: "毛泽东",
  englishName: "Mao Zedong",
  life: "1893—1976",
  englishLife: "1893-1976",
  school: "中国马克思主义",
  englishSchool: "Marxism in China",
} as const;

export const maoThoughts: Thought[] = [
  {
    ...maoIdentity,
    id: "mao-investigation",
    topic: "方法",
    text: "没有调查，没有发言权。",
    english: "Without investigation, there is no right to speak.",
    work: "《反对本本主义》",
    englishWork: "Oppose Book Worship",
    reflection: "判断不能只靠概念在概念中打转。进入现场、辨认条件、听见具体经验，才可能让结论对现实负责。",
    englishReflection: "Judgment cannot remain a circuit of concepts. Entering the situation, identifying its conditions, and hearing concrete experience are what make a conclusion answerable to reality.",
    question: "你正在下结论的那件事，最缺少哪一种一手材料？",
    englishQuestion: "What first-hand evidence is most missing from the conclusion you are drawing?",
    palette: ["#e8e1d4", "#b7a78e", "#756451", "#27231f"],
    rendering: "short-quote",
  },
  {
    ...maoIdentity,
    id: "mao-practice",
    topic: "实践",
    text: "认识从实践中来，也要回到实践中接受检验。",
    english: "Knowledge arises from practice and must return to practice to be tested.",
    work: "《实践论》",
    englishWork: "On Practice",
    reflection: "理解不是一次完成的占有，而是实践、认识、再实践的循环。行动暴露旧认识的边界，也为下一轮判断提供材料。",
    englishReflection: "Understanding is not acquired once and for all. It moves through practice, knowledge, and renewed practice, with action exposing the limits of what we thought we knew.",
    question: "你有哪些确信，还没有经受现实的检验？",
    englishQuestion: "Which of your convictions has not yet been tested by reality?",
    palette: ["#e6dfd1", "#b5a184", "#7e684d", "#2a251f"],
    rendering: "paraphrase",
  },
  {
    ...maoIdentity,
    id: "mao-contradiction",
    topic: "矛盾",
    text: "研究复杂问题，要分清主要矛盾与矛盾的主要方面。",
    english: "To study a complex problem, distinguish its principal contradiction and the principal aspect within it.",
    work: "《矛盾论》",
    englishWork: "On Contradiction",
    reflection: "问题常常不止一个，但它们并不具有相同的分量。抓住此刻最能牵动全局的关系，行动才不会被表面纷杂带走。",
    englishReflection: "Problems rarely come alone, but they do not carry equal weight. Action becomes clearer when we identify the relation that most strongly shapes the whole situation.",
    question: "眼前的复杂局面中，哪一个矛盾真正牵动着其他问题？",
    englishQuestion: "In the complexity before you, which contradiction actually shapes the others?",
    palette: ["#e5ddd0", "#b79d7c", "#7d5e40", "#2b241d"],
    rendering: "paraphrase",
  },
  {
    ...maoIdentity,
    id: "mao-spark",
    topic: "战略",
    text: "判断新生力量，不能只看它此刻有多大，还要看它朝哪里生长。",
    english: "Judge an emerging force not only by its present size, but by the direction in which it is growing.",
    work: "《星星之火，可以燎原》",
    englishWork: "A Single Spark Can Start a Prairie Fire",
    reflection: "静态规模容易遮住动态趋势。战略判断既要拒绝空想，也不能把今天的弱小误认为明天的不可能。",
    englishReflection: "Static scale can conceal a dynamic tendency. Strategic judgment must reject fantasy without mistaking present weakness for future impossibility.",
    question: "你是否因为一件事现在还小，就低估了它的方向？",
    englishQuestion: "Have you underestimated something's direction because it is still small today?",
    palette: ["#e9dfcf", "#c0a47b", "#8a6339", "#2d241a"],
    rendering: "paraphrase",
  },
  {
    ...maoIdentity,
    id: "mao-people-life",
    topic: "群众",
    text: "宏大的目标，必须落到人们正在经历的具体生活里。",
    english: "A large goal must take root in the concrete lives people are actually living.",
    work: "《关心群众生活，注意工作方法》",
    englishWork: "Be Concerned with the Well-Being of the Masses, Pay Attention to Methods of Work",
    reflection: "抽象目标只有进入柴米、住房、疾病与工作的细节，才会成为共同事业，而不只是少数人的口号。",
    englishReflection: "An abstract goal becomes a shared undertaking only when it enters the details of food, housing, illness, and work rather than remaining a slogan for the few.",
    question: "你所坚持的目标，怎样改变一个人的日常处境？",
    englishQuestion: "How does the goal you defend change someone's everyday circumstances?",
    palette: ["#e3e2d5", "#adb099", "#6f765d", "#252720"],
    rendering: "paraphrase",
  },
  {
    ...maoIdentity,
    id: "mao-protracted-war",
    topic: "战略",
    text: "暂时的强弱不是结局；时间、条件与人的行动会改变力量关系。",
    english: "Temporary strength is not the outcome; time, conditions, and human action can transform the balance of forces.",
    work: "《论持久战》",
    englishWork: "On Protracted War",
    reflection: "战略眼光把局势看作过程，而不是定格的画面。既不被眼前困难压倒，也不拿愿望代替条件分析。",
    englishReflection: "Strategic vision treats a situation as a process rather than a frozen image. It neither surrenders to present difficulty nor substitutes wishes for an analysis of conditions.",
    question: "如果把时间加入判断，你对当前困境的结论会改变吗？",
    englishQuestion: "If time were added to your judgment, would your conclusion about the present difficulty change?",
    palette: ["#e1ddd3", "#aba08c", "#716453", "#24221e"],
    rendering: "paraphrase",
  },
  {
    ...maoIdentity,
    id: "mao-art",
    topic: "文化",
    text: "谈文艺，首先要回答它为什么人服务。",
    english: "To discuss art and literature, first ask whom they are meant to serve.",
    work: "《在延安文艺座谈会上的讲话》",
    englishWork: "Talks at the Yenan Forum on Literature and Art",
    reflection: "作品从来不只关乎形式。它选择谁的经验值得被看见、用谁的语言说话，也由此进入社会关系。",
    englishReflection: "A work is never only a matter of form. It chooses whose experience deserves visibility and whose language is spoken, and thereby enters social relations.",
    question: "你正在创作或传播的内容，默认把谁当作了它的读者？",
    englishQuestion: "Whom does the work you create or circulate assume as its audience?",
    palette: ["#e7ddd4", "#b6a093", "#7c6256", "#29221f"],
    rendering: "paraphrase",
  },
  {
    ...maoIdentity,
    id: "mao-mass-line",
    topic: "群众",
    text: "从群众中来，到群众中去。",
    english: "From the masses, to the masses.",
    work: "《关于领导方法的若干问题》",
    englishWork: "Some Questions Concerning Methods of Leadership",
    reflection: "经验需要被集中、整理和形成判断，但判断不能停在少数人手里；它还要回到共同实践中，被理解、修正并变成行动。",
    englishReflection: "Experience must be gathered and shaped into judgment, but judgment cannot remain with the few. It must return to shared practice to be understood, revised, and turned into action.",
    question: "你的方案如何让提出问题的人也参与检验答案？",
    englishQuestion: "How does your proposal let those who raised the problem participate in testing the answer?",
    palette: ["#e2e2d8", "#a9ae9d", "#68705f", "#232621"],
    rendering: "short-quote",
  },
  {
    ...maoIdentity,
    id: "mao-service",
    topic: "群众",
    text: "衡量一项工作的价值，要看它是否增进了共同生活。",
    english: "Measure the value of work by whether it advances a shared life.",
    work: "《为人民服务》",
    englishWork: "Serve the People",
    reflection: "个人意义不必只从自我完成中寻找。把能力放进他人的需要与共同利益之中，也能构成一种有方向的生活。",
    englishReflection: "Personal meaning need not come only from self-realization. Placing one's abilities within others' needs and a common good can also give a life direction.",
    question: "你最擅长的事，能为共同生活增加什么？",
    englishQuestion: "What can the thing you do best add to a shared life?",
    palette: ["#e8e3d7", "#b7aa91", "#786b54", "#28241e"],
    rendering: "paraphrase",
  },
  {
    ...maoIdentity,
    id: "mao-bethune",
    topic: "方法",
    text: "责任心与专业能力，必须在具体工作中彼此完成。",
    english: "Responsibility and professional ability must complete one another in concrete work.",
    work: "《纪念白求恩》",
    englishWork: "In Memory of Norman Bethune",
    reflection: "只有热情而没有能力，善意可能无法抵达结果；只有技术而没有责任，能力也会失去方向。",
    englishReflection: "Good intentions without ability may never reach a result, while technique without responsibility loses its direction.",
    question: "你的认真，是否已经转化为别人可以依赖的能力？",
    englishQuestion: "Has your seriousness become an ability that others can rely on?",
    palette: ["#e1e4df", "#aab6ad", "#66766c", "#222824"],
    rendering: "paraphrase",
  },
  {
    ...maoIdentity,
    id: "mao-yugong",
    topic: "实践",
    text: "看似不可能的困难，也会被持续而共同的行动重新塑形。",
    english: "Even an apparently impossible obstacle can be reshaped by sustained collective action.",
    work: "《愚公移山》",
    englishWork: "The Foolish Old Man Who Removed the Mountains",
    reflection: "坚持不是重复同一个姿势，而是在长时间中组织力量、积累变化，让困难不再保持原来的形状。",
    englishReflection: "Persistence is not repeating the same gesture. Across time it organizes strength and accumulates change until the obstacle no longer keeps its original shape.",
    question: "哪座山并不需要一次推倒，而需要每天改变一点？",
    englishQuestion: "Which mountain need not fall at once, but can be changed a little each day?",
    palette: ["#e7e0d4", "#b4a58d", "#756650", "#26221d"],
    rendering: "paraphrase",
  },
  {
    ...maoIdentity,
    id: "mao-committee",
    topic: "方法",
    text: "工作既要抓住中心，也要让各方面像弹钢琴一样彼此配合。",
    english: "Work must grasp its center while coordinating its parts as one plays a piano.",
    work: "《党委会的工作方法》",
    englishWork: "Methods of Work of Party Committees",
    reflection: "重点并不等于只做一件事。好的组织既知道哪一个音符领奏，也让不同任务在节奏中互相支撑。",
    englishReflection: "A priority does not mean doing only one thing. Good organization knows which note leads while letting different tasks support one another in rhythm.",
    question: "你抓住了中心工作，却忽略了哪一个必须配合的部分？",
    englishQuestion: "Which necessary part have you neglected while focusing on the central task?",
    palette: ["#e4e0d6", "#aea58f", "#6f6654", "#24221d"],
    rendering: "paraphrase",
  },
];

export const maoThoughtConnections: ThoughtConnection[] = [
  {
    source: "mao-investigation",
    target: "mao-practice",
    kind: "reframes",
    summary: "调查把认识带到具体条件之中；《实践论》进一步把这种认识写成实践与认识循环推进的过程。",
    englishSummary: "Investigation grounds knowledge in concrete conditions; On Practice develops this into a recurring movement between practice and understanding.",
  },
  {
    source: "marx",
    target: "mao-practice",
    kind: "reframes",
    summary: "经由马克思主义传统，实践不再只是应用知识，而成为认识产生、修正并获得检验的条件。",
    englishSummary: "Through the Marxist tradition, practice becomes not merely the application of knowledge but the condition of its formation, revision, and testing.",
  },
  {
    source: "descartes",
    target: "mao-practice",
    kind: "contrasts",
    summary: "笛卡尔从可自我确证的思维寻找起点；实践论则把认识置于主体参与并改变现实的活动之中。",
    englishSummary: "Descartes seeks a beginning in self-certifying thought; On Practice locates knowledge in activity that engages and changes reality.",
  },
  {
    source: "hegel",
    target: "mao-contradiction",
    kind: "reframes",
    summary: "经由马克思主义传统，辩证矛盾从观念运动被重构为具体事物内部不平衡、会变化的关系。",
    englishSummary: "Mediated by the Marxist tradition, dialectical contradiction is reframed from a movement of concepts into uneven, changing relations within concrete things.",
  },
  {
    source: "mao-contradiction",
    target: "mao-protracted-war",
    kind: "reframes",
    summary: "对主要矛盾和力量转化的判断，在《论持久战》中成为分析阶段、条件与战略主动性的工具。",
    englishSummary: "The analysis of principal contradiction and changing forces becomes, in On Protracted War, a way to understand stages, conditions, and strategic initiative.",
  },
  {
    source: "mao-spark",
    target: "mao-protracted-war",
    kind: "reframes",
    summary: "从辨认微小力量的发展方向，到分析长期过程中的力量转化，两篇文章共享一种动态的战略时间观。",
    englishSummary: "From reading the direction of a small emerging force to analyzing shifts across a long process, both works share a dynamic sense of strategic time.",
  },
  {
    source: "mao-people-life",
    target: "mao-mass-line",
    kind: "reframes",
    summary: "对具体生活的关切，在群众路线中被组织为收集经验、形成判断并返回共同实践的方法。",
    englishSummary: "Concern for concrete life is organized in the mass line as a method of gathering experience, forming judgment, and returning it to shared practice.",
  },
  {
    source: "mao-practice",
    target: "mao-mass-line",
    kind: "reframes",
    summary: "实践与认识的循环在领导方法中获得组织形式：经验被集中，又在行动中接受新的检验。",
    englishSummary: "The cycle of practice and knowledge gains an organizational form: experience is concentrated and then tested again in action.",
  },
  {
    source: "mao-mass-line",
    target: "mao-committee",
    kind: "reframes",
    summary: "群众路线处理认识从哪里来、回到哪里去；工作方法进一步处理集体如何协调重点、信息与责任。",
    englishSummary: "The mass line asks where knowledge comes from and returns; committee methods ask how a collective coordinates priorities, information, and responsibility.",
  },
  {
    source: "mao-bethune",
    target: "mao-service",
    kind: "resonates",
    summary: "从专业责任到公共价值，两篇文章都把个人能力放到他人的需要和共同事业中衡量。",
    englishSummary: "From professional responsibility to public value, both works measure individual ability within others' needs and a shared undertaking.",
  },
  {
    source: "mao-service",
    target: "mao-yugong",
    kind: "reframes",
    summary: "共同目的为行动提供方向，《愚公移山》则把这种方向展开为长期、协作与累积改变。",
    englishSummary: "A common purpose gives action direction; The Foolish Old Man expands it into duration, cooperation, and cumulative change.",
  },
  {
    source: "mao-art",
    target: "arendt",
    kind: "contrasts",
    summary: "两者都把表达放在共同世界中理解，但前者先问服务对象，阿伦特更强调行动、言说与复数主体的公共显现。",
    englishSummary: "Both place expression in a shared world, but the former begins with whom art serves while Arendt stresses public appearance through action, speech, and plurality.",
  },
];
