export type Thought = {
  id: string;
  name: string;
  englishName: string;
  life: string;
  englishLife: string;
  school: string;
  englishSchool: string;
  topic: "存在" | "伦理" | "知识" | "政治" | "语言";
  text: string;
  english: string;
  work: string;
  englishWork: string;
  reflection: string;
  englishReflection: string;
  question: string;
  englishQuestion: string;
  palette: [string, string, string, string];
};

export const thoughts: Thought[] = [
  {
    id: "socrates",
    name: "苏格拉底",
    englishName: "Socrates",
    life: "约前 470—前 399",
    englishLife: "c. 470-399 BCE",
    school: "古希腊哲学",
    englishSchool: "Ancient Greek Philosophy",
    topic: "知识",
    text: "未经省察的生活，尚未真正成为自己的生活。",
    english: "An unexamined life has not yet truly become one's own.",
    work: "柏拉图《申辩篇》",
    englishWork: "Plato's Apology",
    reflection: "省察不是把每个选择都想得复杂，而是追问：此刻支配我的欲望与判断，真的是我认可的吗？",
    englishReflection: "Examination does not mean overcomplicating every choice. It means asking whether the desires and judgments guiding me are ones I can truly endorse.",
    question: "今天有什么念头，是你从未认真检查过的？",
    englishQuestion: "What thought have you carried today without ever seriously examining it?",
    palette: ["#ece4d7", "#c9b89b", "#8c765c", "#2c2823"],
  },
  {
    id: "plato",
    name: "柏拉图",
    englishName: "Plato",
    life: "约前 427—前 347",
    englishLife: "c. 427-347 BCE",
    school: "古希腊哲学",
    englishSchool: "Ancient Greek Philosophy",
    topic: "知识",
    text: "教育不是把光放进眼睛，而是让灵魂转向光。",
    english: "Education is not the act of putting light into the eyes, but of turning the soul toward the light.",
    work: "《理想国》",
    englishWork: "The Republic",
    reflection: "学习并非单纯积累答案。更重要的变化，是我们开始愿意看向原本回避的事物。",
    englishReflection: "Learning is not simply the accumulation of answers. Its deeper change begins when we become willing to look toward what we once avoided.",
    question: "你正在获得知识，还是正在改变观看世界的方向？",
    englishQuestion: "Are you gaining knowledge, or changing the direction from which you see the world?",
    palette: ["#e7e1d5", "#b3a487", "#7f7159", "#292823"],
  },
  {
    id: "aristotle",
    name: "亚里士多德",
    englishName: "Aristotle",
    life: "前 384—前 322",
    englishLife: "384-322 BCE",
    school: "古希腊哲学",
    englishSchool: "Ancient Greek Philosophy",
    topic: "伦理",
    text: "人的品格，生成于一次又一次的行动之中。",
    english: "Character is formed through action, repeated again and again.",
    work: "《尼各马可伦理学》",
    englishWork: "Nicomachean Ethics",
    reflection: "美德不是偶尔做对一件事，而是通过实践，逐渐成为那个能稳定作出好判断的人。",
    englishReflection: "Virtue is not occasionally doing the right thing. Through practice, we gradually become people capable of making sound judgments reliably.",
    question: "你今天重复的行动，正在把你塑造成怎样的人？",
    englishQuestion: "What kind of person are today's repeated actions shaping you into?",
    palette: ["#eee4d0", "#d1b681", "#a4773d", "#32291f"],
  },
  {
    id: "epicurus",
    name: "伊壁鸠鲁",
    englishName: "Epicurus",
    life: "前 341—前 270",
    englishLife: "341-270 BCE",
    school: "伊壁鸠鲁学派",
    englishSchool: "Epicureanism",
    topic: "伦理",
    text: "真正丰足的人，不是拥有最多，而是需要最少。",
    english: "The truly abundant person is not the one who has the most, but the one who needs the least.",
    work: "《主要教义》",
    englishWork: "Principal Doctrines",
    reflection: "快乐不等于不断增加刺激。减少不必要的欲望，平静本身就会显露出来。",
    englishReflection: "Pleasure is not the endless addition of stimulation. As unnecessary desires diminish, tranquility can reveal itself.",
    question: "哪一种‘必须拥有’，其实可以被轻轻放下？",
    englishQuestion: "Which supposed necessity could you gently let go of?",
    palette: ["#e6ebdc", "#b7c59f", "#7a9364", "#253024"],
  },
  {
    id: "epictetus",
    name: "爱比克泰德",
    englishName: "Epictetus",
    life: "约 50—135",
    englishLife: "c. 50-135 CE",
    school: "斯多葛主义",
    englishSchool: "Stoicism",
    topic: "伦理",
    text: "困扰我们的并非事情本身，而是我们对事情的判断。",
    english: "We are troubled not by things themselves, but by our judgments about them.",
    work: "《手册》",
    englishWork: "Enchiridion",
    reflection: "这不是否认痛苦，而是在事实与解释之间留出一点空间，让我们重新获得行动的自由。",
    englishReflection: "This does not deny suffering. It creates a little space between fact and interpretation, where freedom to act can return.",
    question: "此刻让你不安的，是事实，还是你给事实写下的结论？",
    englishQuestion: "What unsettles you right now: the fact itself, or the conclusion you have written about it?",
    palette: ["#dde7e5", "#a7c0bd", "#668e89", "#223130"],
  },
  {
    id: "augustine",
    name: "奥古斯丁",
    englishName: "Augustine",
    life: "354—430",
    englishLife: "354-430",
    school: "教父哲学",
    englishSchool: "Patristic Philosophy",
    topic: "存在",
    text: "时间若无人问，我仿佛明白；若要说明，我却不再明白。",
    english: "If no one asks me what time is, I seem to know; when I try to explain it, I no longer do.",
    work: "《忏悔录》",
    englishWork: "Confessions",
    reflection: "最熟悉的经验往往最难定义。哲学从这种迟疑开始：让日常重新变得值得惊讶。",
    englishReflection: "Our most familiar experiences are often the hardest to define. Philosophy begins in that hesitation, making the everyday surprising again.",
    question: "有什么你每天经历，却从未真正理解？",
    englishQuestion: "What do you experience every day without ever truly understanding it?",
    palette: ["#e8ded7", "#c6a99a", "#946f60", "#312522"],
  },
  {
    id: "descartes",
    name: "笛卡尔",
    englishName: "René Descartes",
    life: "1596—1650",
    englishLife: "1596-1650",
    school: "理性主义",
    englishSchool: "Rationalism",
    topic: "知识",
    text: "当我怀疑一切时，至少无法怀疑：怀疑正在发生。",
    english: "When I doubt everything, at least I cannot doubt that doubting is taking place.",
    work: "《第一哲学沉思集》",
    englishWork: "Meditations on First Philosophy",
    reflection: "彻底的怀疑并不是为了陷入虚无，而是寻找一个无法被继续动摇的认识起点。",
    englishReflection: "Radical doubt is not meant to leave us in nothingness. It seeks a starting point for knowledge that cannot be shaken any further.",
    question: "如果删去所有未经验证的确信，你还能从哪里开始？",
    englishQuestion: "If every untested certainty were removed, where could you still begin?",
    palette: ["#e5e7e9", "#b6bec5", "#71808d", "#252b31"],
  },
  {
    id: "spinoza",
    name: "斯宾诺莎",
    englishName: "Baruch Spinoza",
    life: "1632—1677",
    englishLife: "1632-1677",
    school: "理性主义",
    englishSchool: "Rationalism",
    topic: "伦理",
    text: "理解一件事，会让我们少一些谴责，多一些自由。",
    english: "To understand something is to condemn less and become more free.",
    work: "《伦理学》",
    englishWork: "Ethics",
    reflection: "看见情感如何被原因推动，并不会消除情感，却可能让我们不再完全受它摆布。",
    englishReflection: "Seeing the causes that move an emotion does not erase it, but it may keep us from being completely ruled by it.",
    question: "若先理解一个人，你对他的判断会不会改变？",
    englishQuestion: "If you understood someone before judging them, how might your judgment change?",
    palette: ["#e2e8df", "#b3c3ad", "#718b6b", "#263025"],
  },
  {
    id: "locke",
    name: "洛克",
    englishName: "John Locke",
    life: "1632—1704",
    englishLife: "1632-1704",
    school: "经验主义",
    englishSchool: "Empiricism",
    topic: "知识",
    text: "心灵并非带着现成观念出生，经验为它写下最初的字迹。",
    english: "The mind is not born with ready-made ideas; experience writes its first marks upon it.",
    work: "《人类理解论》",
    englishWork: "An Essay Concerning Human Understanding",
    reflection: "我们的知识有边界。回到经验，也是在提醒自己：不要把习惯的观念误认作永恒真理。",
    englishReflection: "Knowledge has limits. Returning to experience reminds us not to mistake familiar ideas for eternal truths.",
    question: "你深信不疑的哪种看法，其实来自特定的成长经验？",
    englishQuestion: "Which conviction you hold most firmly may come from a particular experience of growing up?",
    palette: ["#ede8d9", "#ccc09a", "#96865c", "#302c22"],
  },
  {
    id: "hume",
    name: "休谟",
    englishName: "David Hume",
    life: "1711—1776",
    englishLife: "1711-1776",
    school: "经验主义",
    englishSchool: "Empiricism",
    topic: "知识",
    text: "我们看见的是一件事随后发生，因果则是心灵形成的期待。",
    english: "We see one event follow another; causality is the expectation formed by the mind.",
    work: "《人类理解研究》",
    englishWork: "An Enquiry Concerning Human Understanding",
    reflection: "重复让我们产生确定感，但过去一再如此，并不能在逻辑上保证未来仍会如此。",
    englishReflection: "Repetition gives us a feeling of certainty, but the fact that the past has followed a pattern does not logically guarantee the future will do the same.",
    question: "你把哪一种熟悉的模式，当成了必然？",
    englishQuestion: "Which familiar pattern have you mistaken for a necessity?",
    palette: ["#e4e7df", "#bbc2af", "#7f8b71", "#282d25"],
  },
  {
    id: "rousseau",
    name: "卢梭",
    englishName: "Jean-Jacques Rousseau",
    life: "1712—1778",
    englishLife: "1712-1778",
    school: "启蒙哲学",
    englishSchool: "Enlightenment Philosophy",
    topic: "政治",
    text: "服从自己共同参与制定的规则，才可能成为自由。",
    english: "To obey rules we have helped make together is what can make us free.",
    work: "《社会契约论》",
    englishWork: "The Social Contract",
    reflection: "政治自由不是没有约束，而是公共规则不再只是来自他人的强迫，而有我们的共同意志在其中。",
    englishReflection: "Political freedom is not the absence of constraint. It exists when public rules express our shared will rather than merely someone else's force.",
    question: "什么样的规则，能让服从与自由不再矛盾？",
    englishQuestion: "What kind of rule could make obedience and freedom no longer contradict each other?",
    palette: ["#e9e2d9", "#c9b39c", "#94765e", "#302721"],
  },
  {
    id: "kant",
    name: "康德",
    englishName: "Immanuel Kant",
    life: "1724—1804",
    englishLife: "1724-1804",
    school: "德国古典哲学",
    englishSchool: "German Classical Philosophy",
    topic: "伦理",
    text: "人永远不应只被当作手段，也应同时被当作目的。",
    english: "A person should never be treated merely as a means, but always also as an end.",
    work: "《道德形而上学奠基》",
    englishWork: "Groundwork of the Metaphysics of Morals",
    reflection: "尊严意味着：无论目标多么诱人，都不能把一个人的自主性简化成可利用的工具。",
    englishReflection: "Dignity means that no matter how attractive the goal, another person's autonomy cannot be reduced to a tool for our use.",
    question: "你今天的决定，有没有把谁仅仅当成通往结果的手段？",
    englishQuestion: "Has any decision you made today treated someone merely as a means to an outcome?",
    palette: ["#e5e2dc", "#beb6aa", "#847b70", "#292724"],
  },
  {
    id: "hegel",
    name: "黑格尔",
    englishName: "G. W. F. Hegel",
    life: "1770—1831",
    englishLife: "1770-1831",
    school: "德国观念论",
    englishSchool: "German Idealism",
    topic: "存在",
    text: "我们只有穿过矛盾，才能理解一个事物如何成为它自己。",
    english: "Only by passing through contradiction can we understand how something becomes itself.",
    work: "《精神现象学》",
    englishWork: "Phenomenology of Spirit",
    reflection: "矛盾未必是思考失败的标志。事物内部的张力，常常正是变化与发展的动力。",
    englishReflection: "Contradiction need not mark a failure of thought. The tension within a thing is often precisely what drives its change and development.",
    question: "你正在回避的冲突，是否也藏着变化的方向？",
    englishQuestion: "Could the conflict you are avoiding also contain a direction for change?",
    palette: ["#e1e2e6", "#afb3c0", "#6f7489", "#25262e"],
  },
  {
    id: "kierkegaard",
    name: "克尔凯郭尔",
    englishName: "Søren Kierkegaard",
    life: "1813—1855",
    englishLife: "1813-1855",
    school: "存在主义先驱",
    englishSchool: "Forerunner of Existentialism",
    topic: "存在",
    text: "生活只能向后理解，却必须向前生活。",
    english: "Life can only be understood backward, but it must be lived forward.",
    work: "《日记》",
    englishWork: "Journals",
    reflection: "意义经常在经历之后才显现，而行动无法等到一切都被解释清楚才开始。",
    englishReflection: "Meaning often appears only after an experience, while action cannot wait for everything to be fully explained.",
    question: "在无法预知答案时，你愿意迈出哪一步？",
    englishQuestion: "What step are you willing to take when the answer cannot be known in advance?",
    palette: ["#e6e0dd", "#bea9a1", "#876b63", "#2e2523"],
  },
  {
    id: "marx",
    name: "马克思",
    englishName: "Karl Marx",
    life: "1818—1883",
    englishLife: "1818-1883",
    school: "历史唯物主义",
    englishSchool: "Historical Materialism",
    topic: "政治",
    text: "人创造历史，但不是在自己任意选择的条件下创造。",
    english: "People make history, but not under conditions of their own choosing.",
    work: "《路易·波拿巴的雾月十八日》",
    englishWork: "The Eighteenth Brumaire of Louis Bonaparte",
    reflection: "行动者既不是全能的，也不是无力的。自由总在既有结构、历史遗产与现实机会之间展开。",
    englishReflection: "Agents are neither all-powerful nor powerless. Freedom always unfolds among existing structures, historical inheritances, and present opportunities.",
    question: "哪些条件限制着你，哪些条件又能被你改变？",
    englishQuestion: "Which conditions constrain you, and which can you help change?",
    palette: ["#eaded9", "#c7a69c", "#9b695d", "#342522"],
  },
  {
    id: "nietzsche",
    name: "尼采",
    englishName: "Friedrich Nietzsche",
    life: "1844—1900",
    englishLife: "1844-1900",
    school: "生命哲学",
    englishSchool: "Philosophy of Life",
    topic: "存在",
    text: "成为你自己，并不是发现答案，而是持续创造它。",
    english: "Becoming yourself is not a matter of finding the answer, but of continually creating it.",
    work: "《快乐的科学》",
    englishWork: "The Gay Science",
    reflection: "自我不是等待发掘的固定内核。我们通过选择、训练与重新评价，参与自己的生成。",
    englishReflection: "The self is not a fixed core waiting to be uncovered. Through choice, discipline, and revaluation, we participate in our own becoming.",
    question: "如果身份不是答案，你今天想为自己创造什么？",
    englishQuestion: "If identity is not an answer, what would you like to create for yourself today?",
    palette: ["#e8dfd0", "#c9ad7d", "#a07335", "#302719"],
  },
  {
    id: "husserl",
    name: "胡塞尔",
    englishName: "Edmund Husserl",
    life: "1859—1938",
    englishLife: "1859-1938",
    school: "现象学",
    englishSchool: "Phenomenology",
    topic: "知识",
    text: "暂时搁置关于世界的成见，让事物重新显现。",
    english: "Set aside our assumptions about the world for a moment, and let things show themselves again.",
    work: "《纯粹现象学通论》",
    englishWork: "Ideas I",
    reflection: "现象学邀请我们暂停自动判断，仔细描述经验究竟如何出现，而不是急着解释它是什么。",
    englishReflection: "Phenomenology asks us to suspend automatic judgment and describe carefully how experience appears before rushing to explain what it is.",
    question: "若暂时不命名，你眼前的经验是什么样子？",
    englishQuestion: "If you withheld its name for a moment, what would the experience before you be like?",
    palette: ["#e1e8e5", "#aec3bd", "#6f9188", "#23312e"],
  },
  {
    id: "heidegger",
    name: "海德格尔",
    englishName: "Martin Heidegger",
    life: "1889—1976",
    englishLife: "1889-1976",
    school: "现象学",
    englishSchool: "Phenomenology",
    topic: "存在",
    text: "人不是先独自存在，再进入世界；我们从一开始就在世界之中。",
    english: "A person does not first exist alone and then enter the world; from the beginning, we are already in the world.",
    work: "《存在与时间》",
    englishWork: "Being and Time",
    reflection: "自我并非与环境隔绝的内心实体。工具、他人、语言和关切，早已构成我们是谁。",
    englishReflection: "The self is not an inner entity sealed off from its surroundings. Tools, other people, language, and our concerns already compose who we are.",
    question: "你所在的世界，如何悄悄塑造了你？",
    englishQuestion: "How has the world you inhabit quietly shaped who you are?",
    palette: ["#dfe3df", "#aeb9ad", "#718071", "#252b25"],
  },
  {
    id: "wittgenstein",
    name: "维特根斯坦",
    englishName: "Ludwig Wittgenstein",
    life: "1889—1951",
    englishLife: "1889-1951",
    school: "语言哲学",
    englishSchool: "Philosophy of Language",
    topic: "语言",
    text: "一个词的意义，常常就在它被使用的方式里。",
    english: "The meaning of a word often lies in the way it is used.",
    work: "《哲学研究》",
    englishWork: "Philosophical Investigations",
    reflection: "很多哲学困惑来自语言离开了日常使用。回到具体场景，问题有时不是被解答，而是被化解。",
    englishReflection: "Many philosophical confusions arise when language leaves its ordinary use. Back in a concrete situation, a problem may dissolve rather than be answered.",
    question: "你争论的那个词，在彼此口中真的是同一个意思吗？",
    englishQuestion: "Does the word you are arguing about really mean the same thing in each person's mouth?",
    palette: ["#e4e4df", "#bab9ab", "#7e7c6c", "#292924"],
  },
  {
    id: "arendt",
    name: "汉娜·阿伦特",
    englishName: "Hannah Arendt",
    life: "1906—1975",
    englishLife: "1906-1975",
    school: "政治哲学",
    englishSchool: "Political Philosophy",
    topic: "政治",
    text: "行动让新的开始进入世界，而每个人都有开始的能力。",
    english: "Action brings new beginnings into the world, and everyone has the capacity to begin.",
    work: "《人的境况》",
    englishWork: "The Human Condition",
    reflection: "自由不只是内心状态。它在人与人共同出现、说话和行动的公共空间中成为现实。",
    englishReflection: "Freedom is not merely an inner state. It becomes real in the public space where people appear, speak, and act together.",
    question: "你能为共同生活开启一个怎样的新开端？",
    englishQuestion: "What new beginning could you open for a life shared with others?",
    palette: ["#e4e5df", "#b9bcad", "#7e826d", "#282a24"],
  },
  {
    id: "sartre",
    name: "萨特",
    englishName: "Jean-Paul Sartre",
    life: "1905—1980",
    englishLife: "1905-1980",
    school: "存在主义",
    englishSchool: "Existentialism",
    topic: "存在",
    text: "人先存在，然后才通过选择定义自己。",
    english: "A person exists first, and only then defines themselves through choice.",
    work: "《存在主义是一种人道主义》",
    englishWork: "Existentialism Is a Humanism",
    reflection: "没有预先写好的本质替我们承担人生。即使拒绝选择，也已经以一种方式选择了自己。",
    englishReflection: "No prewritten essence can live our life for us. Even refusing to choose is already one way of choosing ourselves.",
    question: "你正用哪些选择，回答‘我是谁’？",
    englishQuestion: "Through which choices are you answering the question, 'Who am I?'",
    palette: ["#e7e0d8", "#c2ad98", "#88705a", "#2c2621"],
  },
  {
    id: "beauvoir",
    name: "西蒙娜·德·波伏瓦",
    englishName: "Simone de Beauvoir",
    life: "1908—1986",
    englishLife: "1908-1986",
    school: "存在主义",
    englishSchool: "Existentialism",
    topic: "政治",
    text: "女人并非纯粹由出生决定，而是在社会处境中被塑造并逐渐成为。",
    english: "One is not simply born a woman; womanhood is shaped and lived within a social situation.",
    work: "《第二性》",
    englishWork: "The Second Sex",
    reflection: "性别身份既不是纯粹天定，也不是凭空自造。社会规范参与塑形，但人仍可能在处境中超越既定角色。",
    englishReflection: "Gendered identity is neither wholly given by nature nor invented from nothing. Social norms shape us, yet people can still move beyond assigned roles from within their situations.",
    question: "你身上的哪些‘应该’，其实来自别人写下的角色？",
    englishQuestion: "Which of the things you feel you 'should' be were written into your role by someone else?",
    palette: ["#eadfe1", "#c8aab1", "#936e79", "#302529"],
  },
  {
    id: "camus",
    name: "加缪",
    englishName: "Albert Camus",
    life: "1913—1960",
    englishLife: "1913-1960",
    school: "荒诞哲学",
    englishSchool: "Philosophy of the Absurd",
    topic: "存在",
    text: "荒诞不是终点；看清它以后，我们仍能选择清醒地生活。",
    english: "The absurd is not the end; after seeing it clearly, we can still choose to live lucidly.",
    work: "《西西弗神话》",
    englishWork: "The Myth of Sisyphus",
    reflection: "世界不保证给出终极答案。反抗不是否认无意义，而是在没有保证时仍创造有限而真实的价值。",
    englishReflection: "The world does not promise a final answer. Revolt does not deny meaninglessness; it creates finite and genuine value without guarantees.",
    question: "即使没有最终答案，什么仍值得你今天去做？",
    englishQuestion: "Even without a final answer, what is still worth doing today?",
    palette: ["#ece1d2", "#d0b07f", "#a37a3f", "#33281d"],
  },
  {
    id: "foucault",
    name: "米歇尔·福柯",
    englishName: "Michel Foucault",
    life: "1926—1984",
    englishLife: "1926-1984",
    school: "当代法国哲学",
    englishSchool: "Contemporary French Philosophy",
    topic: "政治",
    text: "权力不只禁止和压迫，它也生产知识、规范与我们理解自己的方式。",
    english: "Power does not only prohibit and oppress; it also produces knowledge, norms, and the ways we understand ourselves.",
    work: "《规训与惩罚》",
    englishWork: "Discipline and Punish",
    reflection: "权力并不只在高处发号施令，它也藏在分类、测量、习惯以及‘正常’的日常标准里。",
    englishReflection: "Power does not only issue commands from above. It also inhabits classification, measurement, habit, and everyday standards of what counts as normal.",
    question: "你以为自然的标准，是怎样被制造出来的？",
    englishQuestion: "How was the standard you take to be natural actually produced?",
    palette: ["#dfe5e5", "#aebfc0", "#6e898b", "#243032"],
  },
  {
    id: "rawls",
    name: "约翰·罗尔斯",
    englishName: "John Rawls",
    life: "1921—2002",
    englishLife: "1921-2002",
    school: "政治自由主义",
    englishSchool: "Political Liberalism",
    topic: "政治",
    text: "若不知道自己会出生在什么位置，我们会选择怎样的社会规则？",
    english: "If we did not know what position we would be born into, what rules would we choose for society?",
    work: "《正义论》",
    englishWork: "A Theory of Justice",
    reflection: "‘无知之幕’让我们暂时忘记自己的优势与身份，从一个可能成为任何人的位置思考公平。",
    englishReflection: "The veil of ignorance asks us to set aside our advantages and identities, and think about fairness from a position in which we might be anyone.",
    question: "如果你可能成为规则下最不利的人，你还会赞成它吗？",
    englishQuestion: "Would you still endorse a rule if you might become the person most disadvantaged by it?",
    palette: ["#e2e5e8", "#b2bcc5", "#748390", "#252b31"],
  },
  {
    id: "derrida",
    name: "雅克·德里达",
    englishName: "Jacques Derrida",
    life: "1930—2004",
    englishLife: "1930-2004",
    school: "解构主义",
    englishSchool: "Deconstruction",
    topic: "语言",
    text: "意义从不孤立在一个词里，它在与别的词的差异中不断推迟。",
    english: "Meaning never rests in a word alone; it is continually deferred through its differences from other words.",
    work: "《论文字学》",
    englishWork: "Of Grammatology",
    reflection: "语言没有一个完全静止的中心。我们通过差异理解词语，而新的语境总会让意义继续移动。",
    englishReflection: "Language has no perfectly still center. We understand words through difference, and each new context keeps meaning in motion.",
    question: "哪一个看似确定的词，换个语境便有了别的含义？",
    englishQuestion: "Which apparently settled word takes on another meaning when its context changes?",
    palette: ["#e5e1e8", "#bbb0c3", "#7e7089", "#29242f"],
  },
  {
    id: "nussbaum",
    name: "玛莎·努斯鲍姆",
    englishName: "Martha C. Nussbaum",
    life: "1947—",
    englishLife: "1947-present",
    school: "当代伦理学",
    englishSchool: "Contemporary Ethics",
    topic: "伦理",
    text: "正义不只看资源有多少，也看一个人真正能够成为什么、做什么。",
    english: "Justice concerns not only how many resources a person has, but what they are actually able to be and do.",
    work: "《创造能力》",
    englishWork: "Creating Capabilities",
    reflection: "相同资源未必带来相同自由。评价生活质量，还要看人是否拥有把机会变成真实生活的能力。",
    englishReflection: "Equal resources do not necessarily create equal freedom. To assess a life, we must ask whether someone can turn opportunities into real ways of living.",
    question: "你拥有的选择，是名义上的，还是实际可实现的？",
    englishQuestion: "Are the choices available to you merely nominal, or can you actually realize them?",
    palette: ["#e5e8dc", "#bbc5a5", "#7d9066", "#293024"],
  },
];

export type ConnectionKind = "inherits" | "reframes" | "challenges" | "dialogues" | "resonates" | "contrasts";

export type ThoughtConnection = {
  source: string;
  target: string;
  kind: ConnectionKind;
  summary: string;
  englishSummary: string;
};

export const thoughtConnections: ThoughtConnection[] = [
  {
    source: "socrates",
    target: "plato",
    kind: "inherits",
    summary: "柏拉图把苏格拉底的公开追问写成对话，并将“如何生活”展开为灵魂、知识与城邦的问题。",
    englishSummary: "Plato turns Socratic examination into dialogue and expands how to live into questions of soul, knowledge, and the city.",
  },
  {
    source: "socrates",
    target: "epictetus",
    kind: "reframes",
    summary: "斯多葛传统延续了苏格拉底对德性与自我治理的重视，爱比克泰德把它落实为对判断的训练。",
    englishSummary: "The Stoic tradition carries forward Socratic self-governance, while Epictetus turns it into a discipline of judgment.",
  },
  {
    source: "plato",
    target: "aristotle",
    kind: "challenges",
    summary: "亚里士多德保留对善的追问，却把重心从超越的理念转向具体生活中的实践、习惯与判断。",
    englishSummary: "Aristotle keeps the question of the good but shifts attention from transcendent Forms to practice, habit, and judgment.",
  },
  {
    source: "plato",
    target: "augustine",
    kind: "reframes",
    summary: "经由柏拉图主义传统，灵魂向上的转身在奥古斯丁那里成为向内寻找真理、并回归上帝的道路。",
    englishSummary: "Through the Platonist tradition, the soul's upward turn becomes Augustine's inward search for truth and return to God.",
  },
  {
    source: "aristotle",
    target: "nussbaum",
    kind: "reframes",
    summary: "努斯鲍姆重新激活亚里士多德关于人的功能与繁荣的思路，把它改写为人人应拥有的真实能力。",
    englishSummary: "Nussbaum reactivates Aristotle's account of human functioning and flourishing as a theory of real capabilities for everyone.",
  },
  {
    source: "descartes",
    target: "spinoza",
    kind: "challenges",
    summary: "斯宾诺莎继承理性主义的严格推演，却拒绝心物二分，用唯一实体重新解释自由、情感与必然性。",
    englishSummary: "Spinoza keeps rationalist rigor but rejects mind-body dualism, recasting freedom and affect within a single substance.",
  },
  {
    source: "descartes",
    target: "locke",
    kind: "challenges",
    summary: "洛克反对现成的天赋观念，把知识的起点从纯粹理性拉回经验如何在心灵中留下痕迹。",
    englishSummary: "Locke challenges innate ideas and moves the starting point of knowledge from pure reason to the marks left by experience.",
  },
  {
    source: "descartes",
    target: "husserl",
    kind: "reframes",
    summary: "胡塞尔延续第一人称的认识路线，但不再只寻找绝对起点，而是细致描述事物如何向意识显现。",
    englishSummary: "Husserl continues the first-person route, replacing the search for one absolute starting point with a description of how things appear.",
  },
  {
    source: "locke",
    target: "hume",
    kind: "reframes",
    summary: "休谟把经验主义推进得更彻底：若观念来自经验，那么因果、自我与必然性也必须接受同样的检验。",
    englishSummary: "Hume radicalizes empiricism: if ideas come from experience, causality, the self, and necessity must face the same test.",
  },
  {
    source: "hume",
    target: "kant",
    kind: "challenges",
    summary: "休谟对因果的怀疑惊醒康德，促使他追问：经验能够成立，是否因为心灵本身提供了先天形式？",
    englishSummary: "Hume's skepticism about causation awakens Kant to ask whether experience is possible because the mind supplies a priori forms.",
  },
  {
    source: "rousseau",
    target: "kant",
    kind: "reframes",
    summary: "卢梭把自由与共同立法相连；康德把这种思路内化为道德主体对普遍法则的自我立法。",
    englishSummary: "Rousseau links freedom to collective lawmaking; Kant internalizes it as the moral subject's self-legislation of universal law.",
  },
  {
    source: "rousseau",
    target: "rawls",
    kind: "reframes",
    summary: "罗尔斯重启社会契约传统，不再想象一次真实签约，而用“原初状态”检验公平规则。",
    englishSummary: "Rawls renews the social-contract tradition, replacing an actual pact with the original position as a test of fair rules.",
  },
  {
    source: "kant",
    target: "hegel",
    kind: "challenges",
    summary: "黑格尔反对把主体与世界的界限固定下来，转而让理性在矛盾、历史与相互承认中展开。",
    englishSummary: "Hegel refuses a fixed boundary between subject and world and lets reason unfold through contradiction, history, and recognition.",
  },
  {
    source: "kant",
    target: "rawls",
    kind: "reframes",
    summary: "罗尔斯把康德式的平等与自主转译为制度问题：自由而平等的人会接受怎样的正义原则？",
    englishSummary: "Rawls translates Kantian equality and autonomy into an institutional question: what principles would free and equal people accept?",
  },
  {
    source: "hegel",
    target: "kierkegaard",
    kind: "challenges",
    summary: "克尔凯郭尔反对让体系吞没具体的人，强调个体必须在不确定中亲自选择、承担并成为自己。",
    englishSummary: "Kierkegaard resists a system that absorbs the individual, insisting that each person choose and take responsibility amid uncertainty.",
  },
  {
    source: "hegel",
    target: "marx",
    kind: "reframes",
    summary: "马克思保留辩证与历史变化的结构，却把动力从精神的展开转向生产、阶级关系与现实实践。",
    englishSummary: "Marx retains dialectical historical change but relocates its force from Spirit to production, class relations, and practice.",
  },
  {
    source: "kierkegaard",
    target: "heidegger",
    kind: "reframes",
    summary: "海德格尔把焦虑、有限性与个人存在的线索，改写为对“此在”如何在时间中存在的分析。",
    englishSummary: "Heidegger recasts anxiety, finitude, and individual existence as an analysis of how Dasein exists in time.",
  },
  {
    source: "kierkegaard",
    target: "sartre",
    kind: "reframes",
    summary: "萨特把必须亲自选择的存在难题世俗化：没有预设本质，也没有外在保证替人承担自由。",
    englishSummary: "Sartre secularizes the demand for personal choice: no preset essence or external guarantee can assume our freedom for us.",
  },
  {
    source: "marx",
    target: "foucault",
    kind: "reframes",
    summary: "福柯保留对历史结构与支配的敏感，却把分析从阶级扩展到规训、知识与主体如何被生产。",
    englishSummary: "Foucault retains attention to historical domination but expands analysis beyond class to discipline, knowledge, and the production of subjects.",
  },
  {
    source: "nietzsche",
    target: "heidegger",
    kind: "reframes",
    summary: "海德格尔把尼采视为西方形而上学的关键终点，并借这场交锋重新提出存在问题。",
    englishSummary: "Heidegger reads Nietzsche as a decisive culmination of Western metaphysics and uses that encounter to reopen the question of Being.",
  },
  {
    source: "nietzsche",
    target: "foucault",
    kind: "inherits",
    summary: "福柯继承谱系学的锋利：不寻找观念的纯粹起源，而追踪真理、规范与权力的历史生成。",
    englishSummary: "Foucault inherits genealogy's edge, tracing the historical production of truth, norms, and power instead of a pure origin.",
  },
  {
    source: "nietzsche",
    target: "derrida",
    kind: "reframes",
    summary: "德里达延续对固定起源与中心的怀疑，把问题推进到文字、差异与意义不断延后的结构。",
    englishSummary: "Derrida extends suspicion of fixed origins and centers into writing, difference, and the continual deferral of meaning.",
  },
  {
    source: "husserl",
    target: "heidegger",
    kind: "challenges",
    summary: "海德格尔从现象学出发，却不把意识当作终点，而把经验放回在世存在、时间与关切之中。",
    englishSummary: "Heidegger starts from phenomenology but relocates experience from consciousness to being-in-the-world, time, and concern.",
  },
  {
    source: "husserl",
    target: "sartre",
    kind: "reframes",
    summary: "萨特借用意向性理解意识，却把它推向自由、他人目光与自欺等具体的存在处境。",
    englishSummary: "Sartre uses intentionality to understand consciousness, then pushes it toward freedom, the other's gaze, and bad faith.",
  },
  {
    source: "heidegger",
    target: "arendt",
    kind: "reframes",
    summary: "阿伦特把在世存在的线索转向复数的人：共同世界不是背景，而是在言说与行动中被建立。",
    englishSummary: "Arendt turns being-in-the-world toward human plurality: a common world is made through speech and action, not given as background.",
  },
  {
    source: "heidegger",
    target: "sartre",
    kind: "reframes",
    summary: "萨特把“存在先于本质”推向激进自由，较少强调世界的给予，更多强调选择与责任。",
    englishSummary: "Sartre pushes existence before essence toward radical freedom, emphasizing choice and responsibility over the world's givenness.",
  },
  {
    source: "heidegger",
    target: "derrida",
    kind: "challenges",
    summary: "德里达承接对形而上学的拆解，同时追问“存在”是否仍被放在一个过于稳定的中心位置。",
    englishSummary: "Derrida continues the dismantling of metaphysics while asking whether Being still occupies too stable a center.",
  },
  {
    source: "sartre",
    target: "beauvoir",
    kind: "dialogues",
    summary: "这是长期的双向思想对话：两者共同追问自由，波伏瓦更持续地强调身体、性别与社会处境。",
    englishSummary: "This is a sustained two-way dialogue about freedom, with Beauvoir pressing more consistently on body, gender, and social situation.",
  },
  {
    source: "rawls",
    target: "nussbaum",
    kind: "challenges",
    summary: "经由阿马蒂亚·森并由努斯鲍姆发展的能力路径认为，资源与基本善仍不足以衡量真实自由。",
    englishSummary: "The capabilities path developed by Amartya Sen and Nussbaum argues that resources and primary goods cannot fully measure real freedom.",
  },
  {
    source: "hegel",
    target: "beauvoir",
    kind: "reframes",
    summary: "波伏瓦借主奴关系思考性别中的主体与他者，却把抽象承认放回身体、制度和日常生活。",
    englishSummary: "Beauvoir draws on the master-slave relation to think gendered self and other, relocating recognition in bodies, institutions, and daily life.",
  },
  {
    source: "marx",
    target: "beauvoir",
    kind: "reframes",
    summary: "波伏瓦吸收物质处境与劳动的分析，同时拒绝把性别压迫完全还原为阶级关系。",
    englishSummary: "Beauvoir takes up material situation and labor while refusing to reduce gendered oppression entirely to class.",
  },
  {
    source: "heidegger",
    target: "beauvoir",
    kind: "reframes",
    summary: "波伏瓦把有限、在世的存在重新置于性别化处境中，强调自由只能从具体条件内部展开。",
    englishSummary: "Beauvoir relocates finite being-in-the-world within gendered situations, insisting that freedom unfolds only from concrete conditions.",
  },
  {
    source: "heidegger",
    target: "foucault",
    kind: "reframes",
    summary: "福柯延续对现代主体和既有存在方式的怀疑，却转向知识制度、历史实践与权力技术。",
    englishSummary: "Foucault continues the critique of the modern subject but turns toward institutions of knowledge, historical practices, and technologies of power.",
  },
  {
    source: "epicurus",
    target: "camus",
    kind: "resonates",
    summary: "两者都拒绝把好生活押在超越保证上；伊壁鸠鲁寻找宁静，加缪则强调清醒的反抗。",
    englishSummary: "Both refuse to stake a good life on transcendent guarantees; Epicurus seeks tranquility, while Camus stresses lucid revolt.",
  },
  {
    source: "epictetus",
    target: "spinoza",
    kind: "resonates",
    summary: "两者都把自由放在理解关系之中：一个训练判断，一个理解情感与必然性的原因。",
    englishSummary: "Both locate freedom in understanding relations: one disciplines judgment, the other grasps the causes of affects and necessity.",
  },
  {
    source: "epicurus",
    target: "epictetus",
    kind: "contrasts",
    summary: "两种生活疗法都追求不被扰乱：伊壁鸠鲁整理欲望，爱比克泰德则训练我们对事件的判断。",
    englishSummary: "Both offer therapies for disturbance: Epicurus orders desire, while Epictetus disciplines our judgments about events.",
  },
  {
    source: "augustine",
    target: "kierkegaard",
    kind: "resonates",
    summary: "两者都把哲学写成内在生命的紧张：时间、焦虑、信仰与自我不是抽象对象，而是亲身经历。",
    englishSummary: "Both write philosophy as inward tension, where time, anxiety, faith, and selfhood are lived rather than merely abstract.",
  },
  {
    source: "plato",
    target: "hume",
    kind: "contrasts",
    summary: "柏拉图让知识转向可理解的恒常形式；休谟则把知识的边界拉回印象、习惯与可经验之物。",
    englishSummary: "Plato turns knowledge toward stable intelligible forms; Hume draws its limits back to impressions, habit, and experience.",
  },
  {
    source: "aristotle",
    target: "epicurus",
    kind: "contrasts",
    summary: "两者都谈幸福，却给出不同生活节奏：亚里士多德强调德性实践，伊壁鸠鲁强调节制欲望与安宁。",
    englishSummary: "Both pursue happiness but prescribe different rhythms: Aristotelian virtue in practice versus Epicurean tranquility and restrained desire.",
  },
  {
    source: "spinoza",
    target: "kant",
    kind: "contrasts",
    summary: "斯宾诺莎在理解必然性中寻找自由；康德则把自由放在理性主体能够为自己立法之中。",
    englishSummary: "Spinoza finds freedom through understanding necessity; Kant locates it in the rational subject's capacity for self-legislation.",
  },
  {
    source: "spinoza",
    target: "sartre",
    kind: "contrasts",
    summary: "斯宾诺莎在理解必然性中寻找更大的能动，萨特则把不可逃避的选择置于自由的中心。",
    englishSummary: "Spinoza finds greater agency through understanding necessity; Sartre places inescapable choice at freedom's center.",
  },
  {
    source: "descartes",
    target: "heidegger",
    kind: "contrasts",
    summary: "笛卡尔从可自我确证的思维主体出发；海德格尔认为人从来不是孤立意识，而总已在世界之中。",
    englishSummary: "Descartes begins with a self-certifying thinking subject; Heidegger argues that we are never isolated consciousness but always already in a world.",
  },
  {
    source: "hume",
    target: "wittgenstein",
    kind: "resonates",
    summary: "两者都警惕把哲学必然性放得过高，并让习惯、实践和日常使用重新进入思考。",
    englishSummary: "Both distrust inflated philosophical necessity and return thought to habit, practice, and ordinary use.",
  },
  {
    source: "rousseau",
    target: "arendt",
    kind: "resonates",
    summary: "两者都认为自由必须在人与人的共同世界里出现，但一方偏向共同立法，一方偏向公共行动。",
    englishSummary: "Both make freedom public: Rousseau stresses collective lawmaking, while Arendt stresses action in a shared world.",
  },
  {
    source: "hegel",
    target: "camus",
    kind: "contrasts",
    summary: "黑格尔在历史矛盾中寻找可理解的展开；加缪拒绝让历史获得终极保证，坚持有限而清醒的行动。",
    englishSummary: "Hegel seeks intelligible development in historical contradiction; Camus denies history a final guarantee and insists on finite lucid action.",
  },
  {
    source: "hegel",
    target: "foucault",
    kind: "contrasts",
    summary: "黑格尔让历史矛盾进入可理解的发展；福柯的谱系学更强调断裂、偶然与没有预定终点的生成。",
    englishSummary: "Hegel makes historical contradiction part of intelligible development; Foucault stresses rupture, contingency, and change without a preset end.",
  },
  {
    source: "kierkegaard",
    target: "camus",
    kind: "contrasts",
    summary: "两者都正视荒诞与焦虑；克尔凯郭尔走向信仰的跃迁，加缪选择不诉诸超越的清醒反抗。",
    englishSummary: "Both confront anxiety and absurdity; Kierkegaard turns toward faith, while Camus chooses revolt without transcendence.",
  },
  {
    source: "nietzsche",
    target: "sartre",
    kind: "resonates",
    summary: "两者都拒绝固定本质，让自我成为创造与选择的结果；分歧在于价值重估与自由责任的重心不同。",
    englishSummary: "Both reject a fixed essence and make the self an achievement, though they emphasize revaluation and responsibility differently.",
  },
  {
    source: "nietzsche",
    target: "camus",
    kind: "resonates",
    summary: "外在价值失去保证之后，两者都拒绝虚无停摆，并要求人在此世重新创造肯定。",
    englishSummary: "After external values lose their guarantee, both refuse nihilistic paralysis and demand a renewed affirmation within this life.",
  },
  {
    source: "heidegger",
    target: "wittgenstein",
    kind: "resonates",
    summary: "两者都认为许多旧问题来自错误的开端：一个回到存在方式，一个回到语言实践。",
    englishSummary: "Both think inherited problems begin from a bad starting point: one returns to ways of being, the other to linguistic practice.",
  },
  {
    source: "wittgenstein",
    target: "derrida",
    kind: "contrasts",
    summary: "两者都让意义依赖关系与语境；维特根斯坦回到日常用法，德里达则追踪文本中无法封闭的差异。",
    englishSummary: "Both make meaning relational and contextual; Wittgenstein returns to ordinary use, while Derrida follows differences that resist closure.",
  },
  {
    source: "arendt",
    target: "foucault",
    kind: "contrasts",
    summary: "阿伦特突出行动开启新事物的能力；福柯则追问行动者本身如何被权力、知识与规范塑造。",
    englishSummary: "Arendt foregrounds action's power to begin; Foucault asks how the acting subject is itself shaped by power, knowledge, and norms.",
  },
  {
    source: "arendt",
    target: "rawls",
    kind: "contrasts",
    summary: "阿伦特把政治理解为共同出现与行动；罗尔斯更关心一套公平制度应遵循哪些可辩护原则。",
    englishSummary: "Arendt treats politics as appearing and acting together; Rawls asks which defensible principles fair institutions should follow.",
  },
  {
    source: "sartre",
    target: "camus",
    kind: "contrasts",
    summary: "两者都从无保证的世界出发，却对历史、政治承诺与反抗的边界给出不同答案。",
    englishSummary: "Both begin from a world without guarantees but diverge over history, political commitment, and the limits of revolt.",
  },
  {
    source: "beauvoir",
    target: "nussbaum",
    kind: "resonates",
    summary: "两者都认为抽象自由不够：真实能动性取决于身体、制度与社会条件是否允许人展开生活。",
    englishSummary: "Both find abstract freedom insufficient: real agency depends on bodily, institutional, and social conditions.",
  },
  {
    source: "kant",
    target: "nussbaum",
    kind: "resonates",
    summary: "两者都从不可替代的人格尊严出发；努斯鲍姆进一步追问，哪些实际能力才能让尊严成为生活事实。",
    englishSummary: "Both begin from irreducible human dignity; Nussbaum further asks which practical capabilities make dignity real in a life.",
  },
  {
    source: "foucault",
    target: "derrida",
    kind: "contrasts",
    summary: "两者都拆解自明的基础；福柯偏向制度与历史实践的谱系，德里达偏向文本与概念内部的差异。",
    englishSummary: "Both unsettle self-evident foundations; Foucault traces institutions and practices, Derrida differences within texts and concepts.",
  },
  {
    source: "socrates",
    target: "foucault",
    kind: "resonates",
    summary: "从省察生活到“关切自身”，两者都让哲学成为改变主体的实践，而不仅是积累知识。",
    englishSummary: "From the examined life to care of the self, both make philosophy a practice that transforms the subject, not merely accumulated knowledge.",
  },
];
